<?php

class AccessConstants
{
  const LOCK_THE_GAME = 1;
  const SEE_PASSWORDS = 2;
  const VIEW_PLAYERS = 3;
  const ALTER_PRIVILEGES = 4;
  const MANAGE_RAW_MATERIAL_LOCATIONS = 5;
  const ALTER_PASSWORDS = 6;
  const ALTER_ANIMAL_PLACEMENT = 7;
  const MANAGE_MACHINE_PROJECTS = 8;
  const SEND_PRIVATE_MESSAGES = 9;
  const MANAGE_RAW_MATERIALS = 10;
  const ALTER_OBJECTTYPES_AND_VEHICLES = 11;
  const LOCK_ACCOUNTS = 12;
  const MESSAGE_TO_ALL_PLAYERS = 13;
  const REMOVE_PLAYERS = 14;
  const ALTER_LOCATIONS = 15;
  const VIEW_LIST_OF_LOCATIONS = 16;
  const ACCEPT_PLAYERS = 17;
  const VIEW_INTERNAL_STATISTICS = 19;
  const ACCESS_VEHICLE_APPLET = 20;
  const NOTES_MANIPULATION = 22;
  const MAIL_ALL_PLAYERS = 23;
  const MANAGE_ADVERTISEMENTS = 24;
  const ALTER_ANIMAL_TYPES = 25;
  const MANAGE_TRANSLATIONS = 26;
  const CONTROL_OTHER_CHARACTERS = 27;
  const ALTER_CLOTHING_CATEGORIES = 29;
  const SEARCH_CHARACTER_EVENTS = 30;
  const MANAGE_SURVEYS = 31;
  const VIEW_RESEARCH_ON_PLAYERS = 34;
  const MANAGE_RECRUITMENT_PAGE = 35;
  const SEE_DATABASE_STRUCTURE = 36;
  const ALTER_CREDITS = 37;
  const ALTER_EMAIL = 42;
  const MANAGE_EVENT_GROUPS = 47;
  const DECODE_URLS = 49;
  const MANUAL_EVENT_CREATOR_TOOL = 50;
  const SEE_TRAVELS_TIMELINE = 51;
  const SEE_INDIRECT_OBJECT_TRANSFERS = 52;
  const SEE_ADMIN_DATA = 53;
  const AVOID_REDIRECT_ON_NON_CHARACTER_PAGE = 54;
}
