<?php

class EatingConstants
{
  const STOMACH_CAPACITY = 4000;

  const EATING_EFFICIENCY_HUNGER = -5;
  const EATING_EFFICIENCY_HEALTH = 2;
  const EATING_EFFICIENCY_TIREDNESS = -2;
  const EATING_EFFICIENCY_DRUNKENNESS = 2;
}
